# Setup
title:               Rose
tagline:             'Blog'
description:         'Welcome to Rose Blog'
url:                 http://yeony.github.io
baseurl:             ''
paginate:            1

# About/contact
author:
  name:              Yeonhee Jo
  url:               
  email:             yeony59@gmail.com

# Custom vars
version:             1.0.0
