# Setup
title:               Rose
tagline:             'blog'
description:         'Welcome to Rose blog'
url:                 
baseurl:             http://yeony.github.io
paginate:            1

# About/contact
author:
  name:              Yeonhee Jo
  url:               
  email:             yeony59@gmail.com

# Custom vars
version:             1.0.0
